application/auth.py
# -*- coding: utf-8 -*-
"""
User routes for login and signup.
Can easily be used in other apps.

@author: abhin
"""
import functools
from datetime import datetime
from .models import db, User
from flask import render_template, request, flash, redirect, url_for, Blueprint, session, g

#Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@auth_bp.route("/login", methods=['GET', 'POST'])
def login():
    """
    GET: Login form
    POST: Logins in a user and redirects to mylog

    """

    if request.method == 'POST':
        user = User.query.filter_by(name=request.form['uname']).first()  # Validate Login Attempt
        if user and user.check_password(password=request.form['pswd']):
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main_bp.myLog'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template("login.html", user="None")

@auth_bp.route("/signup", methods=['GET', 'POST'])
def signup():
    """
    Creates new users
    GET: Serves the sign up page
    POST: Creates new user and redirects to MyLog Home
    
    """
    if request.method == 'POST':
        username = request.form['uname']
        password = request.form['pswd']
        email = request.form["e-mail"]
        notifications = request.form.get("notif")
        
        existing_user = User.query.filter_by(name=request.form['uname']).first()

        if existing_user is not None:
            flash("A user with that username already exists please enter a new one.")
        else:
            if notifications:
                new_user = User(name=username, email=email, admin=False, recieve_recs=False, created_on=datetime.now())
            else:
                new_user = User(name=username, admin=False, recieve_recs=False, created_on=datetime.now())
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            session.clear()
            session['user_id'] = new_user.id
            return redirect(url_for('main_bp.myLog'))

    return render_template("signup.html", user="None")

@auth_bp.route("/signout")
def signout():
    session.clear()
    return redirect(url_for("main_bp.hello"))

@auth_bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth_bp.login'))

        return view(**kwargs)

    return wrapped_view

application/routes.py
# -*- coding: utf-8 -*-
"""
Routes for the main functionality of the app

@author: abhin
"""

from datetime import datetime
from .models import db, User, Book, BookUpdate, PublicPost, Category
from .auth import login_required
from flask import render_template, request, flash, redirect, url_for, session, g, Blueprint

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route("/")
def hello():
    user = ""
    if g.user is None:
        user = "None"
    return render_template("home.html", user=user)

@main_bp.route("/public")
def all_public_posts():
    posts = PublicPost.query.all()
    user=""
    if g.user is None:
        user = "None"
    return render_template("allpublicposts.html", user=user, posts=posts)

@main_bp.route("/myLog", methods=['GET'])
@login_required
def myLog():
    """
    Shows the user's books and the logs associated with each one'

    """
    user = User.query.filter_by(id=session.get("user_id")).first()
    books = user.books
    cats = user.categories
    return render_template("mylog.html", name=session.get("user_id"), user=user, books=books, cats=cats)

@main_bp.route("/myLog/<int:cat_id>", methods=['GET'])
@login_required
def myLogCat(cat_id):
    """
    Shows the user's books and the logs associated with each one
    for only the specificed category

    """
    user = User.query.filter_by(id=session.get("user_id")).first()
    books = user.books
    selected_books = []
    for book in books:
        if book.cat_id == cat_id:
            selected_books.append(book)
    cats = user.categories
    return render_template("category.html", name=session.get("user_id"), user=user, books=selected_books, cats=cats, curr_cat=cat_id)

@main_bp.route("/readinglist", methods=['GET'])
@login_required
def reading_list():
    user = User.query.filter_by(id=session.get("user_id")).first()
    books = user.books
    book_titles = []
    for b in reversed(books):
        book_titles.append(b.title)
    return render_template("readinglist.html", books = books, titles = book_titles, cats=user.categories)

@main_bp.route("/publicposts", methods=['GET'])
@login_required
def my_public_posts():
    user = User.query.filter_by(id=session.get("user_id")).first()
    posts = user.public_posts

    return render_template("mypublicposts.html", posts = posts, cats=user.categories)

@main_bp.route("/create_update111", methods=['POST'])
@login_required
def update():
    title = request.form['title']
    body = request.form['update']
    pages = request.form['pages']
    date = datetime.now()
    book = Book.query.filter_by(id=request.form['book_num']).first()
    new_update = BookUpdate(title=title, date_created=date, text=body, book_id=book.id, book=book, pages=pages)
    db.session.add(new_update)
    db.session.commit()
    return redirect(url_for("main_bp.myLog"))

@main_bp.route("/categorize_book/<int:book_id>/<int:cat_id>")
@login_required
def cat_book(book_id, cat_id):
    book = Book.query.filter_by(id=book_id).first()
    cat = Category.query.filter_by(id=cat_id).first()
    book.cat_id = cat_id
    book.category = cat
    db.session.commit()
    return redirect(url_for("main_bp.myLog"))


@main_bp.route("/markcomplete/<int:book_id>")
@login_required
def mark_done(book_id):
    book = Book.query.filter_by(id=book_id).first()
    if book is not None:
        book.complete=True
        db.session.commit()
    return redirect(url_for('main_bp.reading_list'))

@main_bp.route("/readingList/updateinfo/<int:book_id>", methods=['GET', 'POST'])
@login_required
def update_book_info(book_id):
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['update']
        author = request.form['author']
        book = Book.query.filter_by(id=book_id).first()
        if book is not None:
            book.title = title
            book.author = author
            book.description = body
            db.session.commit()
        return redirect(url_for("main_bp.reading_list"))
    return redirect(url_for("main_bp.reading_list"))

@main_bp.route("/readingLog/updateLog/<int:log_id>", methods=['GET', 'POST'])
@login_required
def update_log(log_id):
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['update']
        read = request.form['read']
        date = datetime.now()
        log = BookUpdate.query.filter_by(id=log_id).first()
        if log is not None:
            log.title = title
            log.date_created = date
            log.pages = read
            log.text = body
            db.session.commit()
        return redirect(url_for('main_bp.myLog'))
    else:
        return redirect(url_for('main_bp.myLog'))
    

@main_bp.route("/delete/<int:book_id>")
@login_required
def delete(book_id):
    if book_id is not None:
    	book = Book.query.filter_by(id=book_id).first()
    logs = None
    if book is not None:
        logs = book.book_updates
    if logs is not None:
        for log in logs:
            to_delete = BookUpdate.query.filter_by(id=log.id).first()
            db.session.delete(to_delete)
        db.session.delete(book)
        db.session.commit()
    return redirect(url_for('main_bp.reading_list'))

@main_bp.route("/deletelog/<int:log_id>")
@login_required
def delete_log(log_id):
    log = BookUpdate.query.filter_by(id=log_id).first()
    if log is not None:
        db.session.delete(log)
        db.session.commit()
    return redirect(url_for('main_bp.myLog'))

@main_bp.route("/deletecat/<int:cat_id>")
@login_required
def delete_cat(cat_id):
    user = User.query.filter_by(id=session.get("user_id")).first()
    books = user.books
    for book in books:
        if book.cat_id == cat_id:
            book.cat_id = None
            book.category = None
    cat = Category.query.filter_by(id=cat_id).first()
    db.session.delete(cat)
    db.session.commit()
    return redirect(url_for('main_bp.myLog'))

@main_bp.route("/myLog/create_new_cat", methods=['POST', 'GET'])
@login_required
def create_new_cat():
    if request.method == 'POST':
        cat = request.form['title']
        cat_exists = False
        user = User.query.filter_by(id=session.get("user_id")).first()
        for name in user.categories:
            if name.name == cat:
                flash("Category already exists!")
                return redirect(url_for('main_bp.myLog'))
        new_cat = Category(name=cat, user=user, user_id=session.get("user_id"))
        db.session.add(new_cat)
        db.session.commit()
        return redirect(url_for('main_bp.myLog'))
    return redirect(url_for('main_bp.myLog'))

@main_bp.route("/myLog/create_new", methods=['POST', 'GET'])
@login_required
def create_new():
    """
    GET: Returns form to create a new book/article for the current user
    POST: Adds the book/article to the user's table

    """
    if request.method == 'POST':
        title = request.form['title']
        author = request.form['author']
        descrp = request.form['descrp']

        book_exists = False
        user = User.query.filter_by(id=session.get("user_id")).first()
        for book in user.books:
            if book.title == title:
                book_exists = True

        if book_exists:
            flash("A book/article with that title has already been created.")
        else:
            new_book = Book(title=title, complete=False, \
                            author=author, description=descrp, date_started=datetime.now(), user=user, \
                                user_id=session.get('session_id'))
            db.session.add(new_book)
            db.session.commit()
            return redirect(url_for('main_bp.myLog'))
    return render_template("createbook.html")

@main_bp.route("/myLog/create_public_post", methods=['POST', 'GET'])
@login_required
def create_public_post():
    if request.method == 'POST':
        title = request.form['title']
        descrp = request.form['update']

        existing_post = PublicPost.query.filter_by(title=title).first()

        if existing_post is not None:
            flash("A public post with that title has already been created.")
        else:
            user = User.query.filter_by(id=session.get("user_id")).first()
            new_post = PublicPost(title=title, date_created=datetime.now(), user=user, \
                                text = descrp, user_id=session.get('session_id'))
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('main_bp.my_public_posts'))
    return render_template("createpost.html")

@main_bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()

application/templates/allpublicposts.html
{% extends 'layout.html' %}

{% block content %}
<br>
<br>
<br>
<ul class="list-group">
{% for post in posts %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    {{ post.title }} by {{ post.user.name }}
    {{ post.date_created.strftime("%m/%d/%Y") }}
  </li>
  <ul><li>{{post.text}}</li></ul>
{% endfor %}
</ul>

{% endblock %}

application/templates/cat.html
{% extends 'layout.html' %}

{% block content %}
<div class="jumbotron">
    <br>
    <h1 class="display-4">Your Personal Reading Log</h1>
    <a href="{{url_for('main_bp.create_new')}}" class="btn btn-info" role="button">Add New Book/Article</a>
    <a href="{{url_for('main_bp.create_public_post')}}" class="btn btn-primary" role="button">Create a Public Post</a>
    <br>
    <br>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
    <div class="form-inline">
        <form action="{{url_for('main_bp.create_new_cat')}}" method="POST">
          <input type="text" class="form-control" id="title"  name="title" required>
          <button type="submit" class="btn btn-success">Add Category</button>
        </form>
    </div>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item"> <a class="nav-link active" href="#">All&nbsp;</a> </li>
  {% for cat in cats %}
      <li class="nav-item"> <a class="nav-link" href="#">{{cat.name}}</a> </li>
  {% endfor %}
  <li class="nav-item"> <a class="nav-link" href="{{ url_for('main_bp.reading_list')}}">Reading List&nbsp;</a></li>
  <li class="nav-item"> <a class="nav-link" href="{{ url_for('main_bp.my_public_posts')}}">My Public Posts&nbsp;&nbsp;</a></li>

  <div class="btn-toolbar" role="toolbar">

   <div class="btn-group mr-2" role="group"></div>
  </div>
</ul>
<div class="btn-toolbar" role="toolbar"> </div>

<!-- Start of the User's log contents -->
<div class="card text-left">
{% for book in books|reverse %}

  <div class="card-header position-sticky justify-content-between">
      <div class="float-right">
      <small>Category: {{book.category.name}}</small> <br>
      <small class="text-muted">Created {{ book.date_started.strftime("%m/%d/%Y") }}</small>
      </div>
      {% if book.author != "" %}
          <h5 class="mb-1">{{ book.title }} by {{ book.author }}</h5>
      {% else %}
          <h5 class="mb-1">{{ book.title }}</h5>
      {% endif %}
      <p class="mb-1"> {{ book.description }} </p>
  </div>
  <div class="card-body">

  <!-- Logs for the book object -->
  {% for log in book.book_updates|reverse %}
  <div class="list-group">
    <div class="accordion" id="accordionExample">
         <div class="card">
            <div class="card-header" id="headingTwo">
            <div class="float-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                   <button class="btn btn-outline-info" type="button" data-toggle="collapse" area-expanded="false" data-target={{"#logEdit" + log.title|string}}>&#128394;</button>
                   <a href="{{url_for('main_bp.delete_log', log_id=log.id)}}" class="btn btn-outline-danger" role="button">&#10060;</a>
                </div>
            </div>
            <h5 class="mb-0">
              <small class="text-muted">{{ log.date_created.strftime("%m/%d/%Y") }}</small>
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target={{"#collapseTwo" + log.title|string}} aria-expanded="false" aria-controls="collapseTwo">
              {{ log.title }}
              </button>
              <small> {{log.pages}}</small>
            </h5>
            </div>

        <div id={{"collapseTwo" + log.title|string}} class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body">
            {{ log.text }}
          </div>
        </div>
      </div>
     <div id={{"logEdit" + log.title|string}} class="collapse multi-collapse">
      <div class="card-body">
        <form action="{{url_for('main_bp.update_log', log_id=log.id)}}" method="POST">
          <small> Make sure to hit submit before navigating to other tabs </small>
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" value="{{log.title|string}}" name="title" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>
          
          <div class="form-group">
            <label for="read">Chapters/Pages Read</label>
            <input type="read" class="form-control" id="author" value="{{log.pages|string}}" name="read">
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>
          
          <div class="form-group">
            <label for="update">Body: </label>
            <textarea class="form-control" id="update" rows="3" value="{{log.text}}" name="update" required>{{log.text}}</textarea>
          </div>



          <button type="submit" class="btn btn-primary">Update Log</button>
        </form>
      </div>
    </div>
    </div>
  </div>
  {% endfor %}
  <!-- End of logs section -->

  <div class="end">
  
  <button class="btn btn-outline-success" type="button" data-toggle="collapse" area-expanded="false" data-target={{"#log" + loop.index|string}}>New Log</button>
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Categorize
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for cat in cats %}
    <a class="dropdown-item" href="{{url_for('main_bp.cat_book', book_id=book.id, cat_id=cat.id)}}">{{cat.name}}</a>
    {% endfor %}
  </div>

  <div id={{"log" + loop.index|string}} class="collapse multi-collapse">
      <div class="card-body">
        <form action="{{url_for('main_bp.update')}}" method="POST">
          <small> Make sure to hit submit before navigating to other tabs </small>
          <div class="form-group">
            <label for="title">Title of Post</label>
            <input type="text" class="form-control" id="title" placeholder="Title of update" name="title" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>

          <div class="form-group">
            <label for="pages">Pages/Chapters Read</label>
            <input type="text" class="form-control" id="pages" placeholder="Example input" name="pages">
          </div>

          <div class="form-group">
            <label for="update">Body of Update: </label>
            <textarea class="form-control" id="update" rows="3" name="update" required></textarea>
          </div>

          <div class="collapse" id="hidden_data">
              <div class="form-group">
                  <input type="number" id="book_num" value={{book.id}} name="book_num"/>
              </div>
          </div>

          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
    
    </div>
    </div>
{% endfor %}
</div>
{% endblock %}

application/templates/mylog.html
{% extends 'layout.html' %}

{% block content %}
<div class="jumbotron">
    <br>
    <h1 class="display-4">Your Personal Reading Log</h1>
    <a href="{{url_for('main_bp.create_new')}}" class="btn btn-info" role="button">Add New Book/Article</a>
    <a href="{{url_for('main_bp.create_public_post')}}" class="btn btn-primary" role="button">Create a Public Post</a>
    <br>
    <br>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}
    <div class="form-inline">
        <form action="{{url_for('main_bp.create_new_cat')}}" method="POST">
          <input type="text" class="form-control" id="title"  name="title" required>
          <button type="submit" class="btn btn-success">Add Category</button>
        </form>
        <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Delete Category
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for cat in cats %}
            <a class="dropdown-item" href="{{url_for('main_bp.delete_cat', cat_id=cat.id)}}">{{cat.name}}</a>
            {% endfor %}
          </div>
    </div>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item"> <a class="nav-link active" href="#">All&nbsp;</a> </li>
  {% for cat in cats %}
      <li class="nav-item"> <a class="nav-link" href="{{url_for('main_bp.myLogCat', cat_id=cat.id)}}">{{cat.name}}</a> </li>
  {% endfor %}
  <li class="nav-item"> <a class="nav-link" href="{{ url_for('main_bp.reading_list')}}">Reading List&nbsp;</a></li>
  <li class="nav-item"> <a class="nav-link" href="{{ url_for('main_bp.my_public_posts')}}">My Public Posts&nbsp;&nbsp;</a></li>

  <div class="btn-toolbar" role="toolbar">

   <div class="btn-group mr-2" role="group"></div>
  </div>
</ul>
<div class="btn-toolbar" role="toolbar"> </div>

<!-- Start of the User's log contents -->
<div class="card text-left border-dark mb-3">
{% for book in books|reverse %}

  <div class="card-header position-sticky justify-content-between">
      <div class="float-right">
      <small>Category: {{book.category.name}}</small> <br>
      <small class="text-muted">Created {{ book.date_started.strftime("%m/%d/%Y") }}</small>
      </div>
      {% if book.author != "" %}
          <h5 class="mb-1">{{ book.title }} by {{ book.author }}</h5>
      {% else %}
          <h5 class="mb-1">{{ book.title }}</h5>
      {% endif %}
      <p class="mb-1"> {{ book.description }} </p>
  </div>
  <div class="card-body">

  <!-- Logs for the book object -->
  {% for log in book.book_updates|reverse %}
  <div class="list-group">
    <div class="accordion" id="accordionExample">
         <div class="card">
            <div class="card-header" id="headingTwo">
            <div class="float-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                   <button class="btn btn-outline-info" type="button" data-toggle="collapse" area-expanded="false" data-target={{"#logEdit" + log.title|string}}>&#128394;</button>
                   <a href="{{url_for('main_bp.delete_log', log_id=log.id)}}" class="btn btn-outline-danger" role="button">&#10060;</a>
                </div>
            </div>
            <h5 class="mb-0">
              <small class="text-muted">{{ log.date_created.strftime("%m/%d/%Y") }}</small>
              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="{{"#collapseTwo" + log.id|string}}" aria-expanded="false" aria-controls="collapseTwo">
              {{ log.title }}
              </button>
              <small> {{log.pages}}</small>
            </h5>
            </div>

        <div id="{{"collapseTwo" + log.id|string}}" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body">
            {{ log.text }}
          </div>
        </div>
      </div>
     <div id={{"logEdit" + log.title|string}} class="collapse multi-collapse">
      <div class="card-body">
        <form action="{{url_for('main_bp.update_log', log_id=log.id)}}" method="POST">
          <small> Make sure to hit submit before navigating to other tabs </small>
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" value="{{log.title|string}}" name="title" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>
          
          <div class="form-group">
            <label for="read">Chapters/Pages Read</label>
            <input type="read" class="form-control" id="author" value="{{log.pages|string}}" name="read">
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>
          
          <div class="form-group">
            <label for="update">Body: </label>
            <textarea class="form-control" id="update" rows="3" value="{{log.text}}" name="update" required>{{log.text}}</textarea>
          </div>



          <button type="submit" class="btn btn-primary">Update Log</button>
        </form>
      </div>
    </div>
    </div>
  </div>
  {% endfor %}
  <!-- End of logs section -->

  <div class="end">
  
  <button class="btn btn-outline-success" type="button" data-toggle="collapse" area-expanded="false" data-target={{"#log" + loop.index|string}}>New Log</button>
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Categorize
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for cat in cats %}
    <a class="dropdown-item" href="{{url_for('main_bp.cat_book', book_id=book.id, cat_id=cat.id)}}">{{cat.name}}</a>
    {% endfor %}
  </div>

  <div id={{"log" + loop.index|string}} class="collapse multi-collapse">
      <div class="card-body">
        <form action="{{url_for('main_bp.update')}}" method="POST">
          <small> Make sure to hit submit before navigating to other tabs </small>
          <div class="form-group">
            <label for="title">Title of Post</label>
            <input type="text" class="form-control" id="title" placeholder="Title of update" name="title" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>

          <div class="form-group">
            <label for="pages">Pages/Chapters Read</label>
            <input type="text" class="form-control" id="pages" placeholder="Example input" name="pages">
          </div>

          <div class="form-group">
            <label for="update">Body of Update: </label>
            <textarea class="form-control" id="update" rows="3" name="update" required></textarea>
          </div>

          <div class="collapse" id="hidden_data">
              <div class="form-group">
                  <input type="number" id="book_num" value={{book.id}} name="book_num"/>
              </div>
          </div>

          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
    
    </div>
    </div>
{% endfor %}
</div>
{% endblock %}

application/templates/readinglist.html
{% extends 'layout.html' %}

{% block content %}
<div class="jumbotron">
    <br>
    <h1 class="display-4">Your Personal Reading Log</h1>
    <a href="{{url_for('main_bp.create_new')}}" class="btn btn-info" role="button">Add New Book/Article</a>
    <a href="{{url_for('main_bp.create_public_post')}}" class="btn btn-primary" role="button">Create a Public Post</a>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item"> <a class="nav-link" href="{{url_for('main_bp.myLog')}}">All&nbsp;</a> </li>
  {% for cat in cats %}
       <li class="nav-item"> <a class="nav-link" href="{{url_for('main_bp.myLogCat', cat_id=cat.id)}}">{{cat.name}}</a> </li>
  {% endfor %}
  <li class="nav-item"> <a class="nav-link active" href="#">Reading List&nbsp;</a></li>
  <li class="nav-item"> <a class="nav-link" href="{{ url_for('main_bp.my_public_posts')}}">My Public Posts&nbsp;&nbsp;</a></li>
      
  <div class="btn-toolbar" role="toolbar">
        
   <div class="btn-group mr-2" role="group"></div>
  </div>
</ul>
<div class="btn-toolbar" role="toolbar"> </div>

<ul class="list-group">
{% for book in books|reverse %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <b>{{titles[loop.index-1]}}</b>
    {% if book.complete %}
    <div class="btn-group" role="group" aria-label="Basic example">
       <a href="#" class="btn btn-success" role="button">Finished!</a>
       <a href="{{url_for('main_bp.delete', book_id=book.id)}}" class="btn btn-danger" role="button">Delete</a>
    </div>
    {% else %}
    <div class="btn-group" role="group" aria-label="Basic example">
      <a href="{{ url_for('main_bp.mark_done', book_id=book.id) }}" class="btn btn-outline-success" role="button">Mark as Complete</a>
      <button class="btn btn-outline-info" type="button" data-toggle="collapse" area-expanded="false" data-target={{"#log" + loop.index|string}}>Edit</button>
      <a href="{{ url_for('main_bp.delete', book_id=book.id) }}" class="btn btn-outline-danger" role="button">Delete</a>
    </div>
    {% endif %}
  </li>
  <div id={{"log" + loop.index|string}} class="collapse multi-collapse">
      <div class="card-body">
        <form action="{{url_for('main_bp.update_book_info', book_id=book.id)}}" method="POST">
          <small> Make sure to hit submit before navigating to other tabs </small>
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" value="{{titles[loop.index-1]}}" name="title" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
          </div>
          
          <div class="form-group">
            <label for="author">Author</label>
            {% if book.author %}
            <input type="text" class="form-control" id="author" value="{{book.author}}" name="author">
            {% else %}
            <input type="text" class="form-control" id="author" name="author">
            {% endif %}
          </div>
          
          <div class="form-group">
            <label for="update">Description: </label>
            <textarea class="form-control" id="update" rows="3" value="{{book.description}}" name="update"></textarea>
          </div>

          <button type="submit" class="btn btn-primary">Update Book Info</button>
        </form>
      </div>
    </div>
{% endfor %}
</ul>
  
  
</div>
{% endblock %}